Trying again
Ali-D-Akbar/weatherman pull request #1
Opened 2019-07-05 07:34 UTC by Ali-D-Akbar

2019-07-08 08:10 UTC, asamolion requested changes

2019-07-08 08:10 UTC, asamolion commented on weatherman.py
> +def mk_int(s):
Use more descriptive function names.

2019-07-08 08:10 UTC, asamolion commented on weatherman.py
> +def mk_double(s):
Please try to use built-in functions. No need to re-invent the wheel.

2019-07-08 08:10 UTC, asamolion commented on weatherman.py
> +        # print(record)
Never push commented code to github.

2019-07-08 08:10 UTC, asamolion commented on weatherman.py
> +months = ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
No need to create an empty value for the string index modification. Use 0 as the first index.

2019-07-08 08:10 UTC, asamolion commented on weatherman.py
> +            file = open(filePath.format(directory, year, months[month]))
Since the file is a .CSV file, you can use the python csv module to ease in the parsing of files.

https://docs.python.org/3/library/csv.html

2019-07-08 08:10 UTC, asamolion commented on weatherman.py
> +                monthly_report.maxMeanTemp = weather_reading.meanTempC
Use snake_case in all variable names.

2019-07-08 08:10 UTC, asamolion commented on weatherman.py
> +            file = open(filePath.format(directory, year, months[month]))
Use the with keyword for file opening and closing.

2019-07-08 08:10 UTC, asamolion commented on weatherman.py
> +directory = sys.argv[1]
Encapsulate this in a main function.

2019-07-08 08:10 UTC, asamolion commented on weatherman.py
> +    argument = sys.argv[i]
use [argparse](https://docs.python.org/3/library/argparse.html) for handling cmd line arguments.

2019-07-08 08:10 UTC, asamolion commented on weatherman.py
> +        flag = False
Why is this variable declared?

2019-07-08 08:10 UTC, asamolion commented on weatherman.py
> +            while weather_reading is not None:
This code is being duplicated. Please try to make it DRY.

2019-07-08 09:34 UTC, Ali-D-Akbar commented on weatherman.py
> +def mk_double(s):
made a function because I wanted to remove replication of try-except block. this is more handy and concise.

2019-07-08 09:34 UTC, Ali-D-Akbar commented on weatherman.py
> +def mk_int(s):
done

2019-07-08 09:34 UTC, Ali-D-Akbar commented on weatherman.py
> +months = ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
done

2019-07-08 09:43 UTC, Ali-D-Akbar commented on weatherman.py
> +        # print(record)
removed

2019-07-08 09:54 UTC, Ali-D-Akbar commented on weatherman.py
> +        flag = False
it's been removed. it was not needed

2019-07-08 10:07 UTC, Ali-D-Akbar commented on weatherman.py
> +directory = sys.argv[1]
done

2019-07-08 13:39 UTC, Ali-D-Akbar commented on weatherman.py
> +    argument = sys.argv[i]
done

2019-07-08 13:47 UTC, Ali-D-Akbar commented on weatherman.py
> +            while weather_reading is not None:
simplified my code

2019-07-09 07:58 UTC, asamolion requested changes

2019-07-09 07:58 UTC, asamolion commented on weatherman.py
> +def print_red(skk): print("\033[91m {}\033[00m".format(skk), end='')
Please name the arguments clearly. Also add docstrings to these methods.

2019-07-09 07:58 UTC, asamolion commented on weatherman.py
> +class WeatherReading:
Add docstring to this and all classes.

2019-07-09 07:58 UTC, asamolion commented on weatherman.py
> +            self.meanHumidity = make_int(self.meanHumidity)
Make all variables snake case.

2019-07-09 07:58 UTC, asamolion commented on weatherman.py
> +                            str1 = ("+" * weather_reading.min_temp)
use more descriptive variable names.

2019-07-09 07:58 UTC, asamolion commented on weatherman.py
> +    def one_horizontal(self, directory, year, month):
This logic is being duplicated. Use `display_bars` directly where needed.

2019-07-09 09:37 UTC, Ali-D-Akbar commented on weatherman.py
> +def print_red(skk): print("\033[91m {}\033[00m".format(skk), end='')
done

2019-07-09 09:37 UTC, Ali-D-Akbar commented on weatherman.py
> +class WeatherReading:
done

2019-07-09 09:37 UTC, Ali-D-Akbar commented on weatherman.py
> +            self.meanHumidity = make_int(self.meanHumidity)
done

2019-07-09 09:43 UTC, Ali-D-Akbar commented on weatherman.py
> +                            str1 = ("+" * weather_reading.min_temp)
renamed

2019-07-09 09:43 UTC, Ali-D-Akbar commented on weatherman.py
> +    def one_horizontal(self, directory, year, month):
duplicated logic removed

2019-07-09 09:59 UTC, asamolion requested changes

2019-07-09 09:59 UTC, asamolion commented on weatherman.py
> +    def calculate_annual_report(self, directory, year):
Add docstrings to the methods as well.

2019-07-09 10:46 UTC, asamolion approved these changes

2019-07-09 10:47 UTC, merged